config/routes.rb
HearthTrack::Application.routes.draw do
  resources :decks

  resources :games

  root "games#index"

  

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  HEROES = %w[Warrior Shaman Rogue Paladin Hunter Druid Warlock Mage Priest]

  has_many :games, dependent: :destroy
  validates :hero_class,:deck_name,:version, presence:true 

  def wins
    games.where(did_i_win: true).count
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  OPPONENTS = %w[Warrior Shaman Rogue Paladin Hunter Druid Warlock Mage Priest]

  belongs_to :deck

  validates :deck, :opponent_class, presence: true
  validates :opponent_class, inclusion: OPPONENTS

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include CurrentDeck
  require 'googlecharts'
  protect_from_forgery with: :exception


  protected

  def graphme(data)
    Gchart.line(  :size => '200x300', 
                :title => "example title",
                :bg => 'efefef',
                :legend => ['first data set label', 'second data set label'],
                :data => [10, 30, 120, 45, 72])
  end

end

app/controllers/concerns/current_deck.rb
module CurrentDeck
  extend ActiveSupport::Concern
  private
    def set_deck
      @deck = Deck.find(session[:deck_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to decks_path
    end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
    # if request.xhr?
    #   render json: {"whatever" => "value"}
    # else
    #   render
    # end
  end

  # def address_lookup
  #   render json: {"whatever" => "value"}
  # end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render action: 'show', status: :created, location: @deck }
      else
        format.html { render action: 'new' }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:hero_class, :deck_name, :version)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    if params[:deck_id] == nil
      @games = Game.all
    else
      @games = Deck.find(params[:deck_id]).games
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @graph = graphme([10])
  end

  # GET /games/new
  def new
    if params[:deck_id] == nil
      redirect_to decks_path, :notice => "select or create a deck first"
      return
    else
      session[:deck_id] = params[:deck_id]
      @deck = Deck.find(params[:deck_id])
      @game = Game.new
    end
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @deck = Deck.find(session[:deck_id])
    game_params[:deck] = @deck
    @game = @deck.games.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:deck, :opponent_class, :did_i_win)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table border=1>
    <tr>
      <th>Hero class</th>
      <th>Deck name</th>
      <th>Version</th>
      <th></th>
    </tr>
    <tr>
      <td>
        <%= f.select :hero_class, Deck::HEROES %>
      </td>
      <td>
        <%= f.text_field :deck_name %>
      </td>
      <td>
        <%= f.number_field :version %>
      </td>
      <td>
        <%= f.submit %>
      </td>
    </tr>
  </table>
  <% end %>

app/views/decks/edit.html.erb
<h1>Editing deck</h1>

<%= render 'form' %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<h1>Listing decks</h1>
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Hero class</th>
      <th>Deck name</th>
      <th>Version</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.hero_class %></td>
        <td><%= deck.deck_name %></td>
        <td><%= deck.version %></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
        <td><%= link_to 'Delete deck', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Game stats', games_path(deck_id: deck) %></td>
        <td><%= link_to 'Add game', new_game_path(deck_id: deck)  %></td>
      </tr>
    <% end %>
      <tr>
        <td><%= link_to 'New Deck', new_deck_path %></td>
      </tr>
      <%= form_for :deck do |f| %>
        <%= f.select :deck, options_for_select(@decks.collect { |deck|
          [deck.deck_name.titleize, deck.id] }), {include_blank: true}, 
            { id: 'games_select' } %>
          <%= f.text_field :wins  %>
          <%= f.submit "Go!" %>
          <% end %>
        </tbody>
      </table>

      <br>

app/views/decks/new.html.erb
<h1>New deck</h1>

<%= render 'form' %>

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hero class:</strong>
  <%= @deck.hero_class %>
</p>

<p>
  <strong>Deck name:</strong>
  <%= @deck.deck_name %>
</p>

<p>
  <strong>Version:</strong>
  <%= @deck.version %>
</p>

<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Back', decks_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table border=1>
    <tr>
      <th>Deck</th>
      <th>opponent</th>
      <th>win?</th>
    </tr>
    <tr>
      <td>
        <%= @deck.deck_name %>
      </td>
      <td>
        <%= f.select :opponent_class, Game::OPPONENTS %>
      </td>
      <td>
        <%= f.check_box :did_i_win %>
      </td>
      <td>
        <%= f.submit %>
      </td>
    </tr>
  </table>
  <% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Deck</th>
      <th>Opponent class</th>
      <th>Did i win</th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr class="<%= cycle('game_line_even','game_line_odd') %>" >
        <td class="deck_name" ><%= game.deck.deck_name %></td>
        <td><%= game.opponent_class %></td>
        <td><%= game.did_i_win %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
      <tr><td> <%= link_to 'New Game', new_game_path %> </tr>
  </tbody>
</table>

<br>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'list games', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deck:</strong>
  <%= @game.deck.deck_name %>
</p>

<p>
  <strong>Opponent class:</strong>
  <%= @game.opponent_class %>
</p>

<p>
  <strong>Did i win:</strong>
  <%= @game.did_i_win %>
</p>
<p>
  <%= @graph %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'game list', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hearthstone Personal Game Tracker</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class='<%= controller.controller_name %>'>
    <div id='banner'>
      <%= @page_title || "Hearthstone Personal Game Tracker" %>
    </div>
    <div id='columns'>
      <div id='side'>
        <li><%= link_to 'Games', games_path %></li>
        <li><%= link_to 'Decks', decks_path %></li>
      </div>
      <div id='main'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>